### PR TITLE
Fix: Fix Desktop rhombus bug on Safari

### LINKED ISSUE #174: Investigate split rectangle on Press/Resources in Mobile
@segacy1 notes that in Chrome on an iPhone 12 there is a funky split between the top paragraph and the pills in the colored rectangles:

split rectangle

@thekaveman was unable to reproduce in Chrome/Firefox responsive view at 320px and higher.

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #174 fully

- Used https://yoksel.github.io/relative-clip-path/ to create clip-paths directly from svg's from Figma. Tried using https://www.plantcss.com/css-clip-path-generator but the shapes were not coming out the same.
- Avoid use of `filter: url` entirely, b/c it's very buggy on Safari.
- Creates an includes for the Press and Resources SVG, as they use the same one.
- Adds SVGs in-line for all 3 Index page SVGs.
- Adds back box-shadow (using filter) on the bottom 2 rhombuses on Home page (https://css-tricks.com/using-box-shadows-and-clip-path-together/)
- This PR also fixes: the second point on #178

## How to test
- Apple/Mac OS: test on Safari, Firefox, Chrome for rhombus fixes
- Windows: test on Firefox, Chrome for no regressions
- Android: test on Chrome for no regressions
- iPhone: test on Safari for no regressions

## Before & After

image
image
Safari behaves very strangely with `filter: url()` -- the browser is trying to apply the filter to _everything_, from the link hover effect, to even the way the user highlights the text. There is no way to apply the filter to just one element in Safari, the browser will apply it to every child element and even highlighted text. And there's no way to add another filter to undo a url filter.

|Before   | After  |
|---|---|
|image|  image |  
|Totally bonkers.   |Normal.|  

image

image

### CODE REVIEW

**Comment by thekaveman** [comment]
@segacy1 when you have some time, can you please review this follow-up to the split rhombuses in Mac/Safari -- this time for Desktop widths. (And please ensure no regressions in Mobile as well).

**Review by thekaveman — CHANGES_REQUESTED** [review]
Regressions on homepage Contact rhombuses, in Windows/Desktop Firefox and Chrome:

* Bottoms are no longer aligned
* The direction changed and no longer represents the Figma design

**Figma**

image

**Staging**

Bottom of each rhombus is aligned, direction "towards" each other as shown in Figma:

image

**This PR**

Bottom of the left rhombus is lower than the bottom of the right rhombus, direction "away" from each other:

image

**Comment by machikoyasuda** [comment]
Fixes pushed:

- Switches the shapes around
- Uses flex-box to manage / keep the heights the same
- Adds back shadow

Safari:
image
image

Firefox:
image
image

**Review by segacy1 — APPROVED** [review]

**Review by thekaveman — APPROVED** [review]
Looks great! Confirmed the fix in Desktop Firefox/Chrome on Windows.

Also, thank you for removing that inline style definition 😁

**Pull request merged**
