### PR TITLE
Add CashApp case study PDF

### LINKED ISSUE #51: PDF to upload / host (but not yet link to content)
Hi, @thekaveman and team! Gillian and Lilly asked that we:
- [ ] upload this [Cal-ITP_CashApp_CaseStudy.pdf](https://github.com/cal-itp/calitp.org/files/9597582/Cal-ITP_CashApp_CaseStudy.pdf) for hosting on calitp.org 

(But not link it to site content yet.)

Not sure if it's as compressed as you'd like. I think that Chris Arvin (who has dropped off this project) compressed it as part of their routine export process, but I am not sure.

Thanks in advance for uploading this as soon as you're able! We will then link to it from our bitly linked-in-bio microsite.

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #51

### CODE REVIEW

**Comment by thekaveman** [comment]
@esquared415 the PDF is live in preview here: https://deploy-preview-52--cal-itp-website.netlify.app/assets/Cal-ITP.CashApp.CaseStudy.pdf. Take a look and let me know. 

I will note the title of the PDF (the document itself, not the content inside) makes the page title a little funky (see the browser tab when you open it: `Letter - 11`). This may be fixable by someone with editing capability on the source/PDF, I think it is one of the document properties.

**Comment by esquared415** [comment]
Ahhh, so funky @thekaveman—sorry about that! I was able to override Chris Arvin's original naming convention in the PDF's properties. Here's that file again with the "Title" corrected in the Properties field.

[calitp_cashapp_casestudy.pdf](https://github.com/cal-itp/calitp.org/files/9600960/calitp_cashapp_casestudy.pdf)

**Review by esquared415 — CHANGES_REQUESTED** [review]
Please upload revised PDF (shared [here](https://github.com/cal-itp/calitp.org/pull/52#issuecomment-1251308966)), which retains same filename but fixes issue with internal doc properties' "Title." Thanks!

**Comment by thekaveman** [comment]
@esquared415 Updated!

**Review by esquared415 — APPROVED** [review]
Looks awesome now—thanks ever so much @thekaveman! 😄

**Pull request merged**
