### PR TITLE
Customer stories & Partners: New pages and homepage updates

### LINKED ISSUE #351: Partners page and home copy update
## Changes request
- Create new Partners page with design, photos, content on Figma.
- Change last graf in home page blurb and add images:
image

- Use Contact template from #355 

## New styles
- Pull quote link style
- One new text/link style to be added.

## Special instructions
- Deploy this branch separately so that it can be sent to Partners for approval

### LINKED ISSUE #354: Customer stories page and home page stats
## Changes requested
- New page, customer stories
- Add this new page to the nav
- Add new stats section to the homepage, which links to the customer stories page

## New styles needed
- New yellow color
- Border radius'ed image class
- Stat font style
- Pulled quote style
- New grey skinny link style
- Photo caption style
- Bullet points
- Linked superscript
- Source

## Assets
- California map
- 4 photos

## New component
- Side by side stat component

## Preview deploy
Make a branch to deploy so this can be approved separately from the Partners page

### LINKED ISSUE #356: Customer stories page: Side-bar topic chooser component
Separating this out from the main ticket #354 

## Component behavior
- User can click on any of the 6 links to be scrolled to the appropriate header area
- When the Impact stat section goes over the component, a slide gradient should appear

## Research
- Double check a11y requirements any any ARIA labels, etc.

## Styles
- Use the muted link style

### LINKED ISSUE #382: Annotation updates
- Add back emoji to link up to annotations (where needed)  ↩️
- [Partners page] move annotation to bottom of each org's section

### LINKED ISSUE #391: Last mile copy updates for staging link 8/1
**HOMEPAGE** 

Replace:

We are proud to work collaboratively with a number of [partner agencies](https://deploy-preview-377--cal-itp-website.netlify.app/partners) within the state of California to help us reach our goals.

With 

We are proud to collaborate with others in the state of California to help us reach our ambitious goals. Learn more about [Our Partners](https://deploy-preview-377--cal-itp-website.netlify.app/partners).

**IMPACT ACROSS CALIFORNIA** 

Replace:

Number of trips using a contactless credit/debit card (YTD)

With 

Trips using a contactless credit/debit card (YTD)\

**PARTNERS** 

Update first CDT stat to: 

68% 
Increase in reduced fare transactions

### LINKED ISSUE #398: Copy updates from staging review for calitp.org
**PARTNERS** 

- [x] Add CARB quote: 
“In order to unlock the greenhouse gas reductions and mobility justice opportunities that transit provides, we have to make it easier for people to use California’s buses and trains. Cal-ITP tackles basic but essential challenges that transit users face so that more Californians can make the switch to sustainable transportation options.” Lisa Macumber, chief of CARB’s Equitable Mobility Incentives branch.

**CUSTOMER STORIES**

- [x] Add ridership Source: https://www.transit.dot.gov/ntd/data-product/2022-annual-database-agency-mode-service

### LINKED ISSUE #403: Update VCTC + MST photos in stories
Update agency photos with 1x + 2x:
customerstories-story-MST
customerstories-story-MST@2x
alt text: A man in a wheelchair boarding a MST bus via a wheelchair lift. The bus is blue with a waving American flag decal across the top. The bus is making a stop at a wide sidewalk. 

stories-main-GlennCounty
stories-main-GlennCounty@2x
alt text: An accessible bus with doors open, showing a smiling bus driver inside. The bus is labeled "Glenn Ride" and parked in a sunlit lot with trees in the background.

Q: do you need separate assets for mobile or will you reuse these?

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #351 
closes #354 
closes #356 
closes #382 
closes #391 
closes #398 
closes #403 

## What this PR does
- Partners page
- Customer stories page
- Homepage update

## Plan for PR

- [x] Gillian approval 9/9
- [x] CalSTA approval

## How to review this PR
- [x] Run a11y tests on all new pages and homepage
- [x] Check copy

## Test

This preview link has all the new updates: https://deploy-preview-377--cal-itp-website.netlify.app/
https://deploy-preview-377--cal-itp-website.netlify.app/customer-stories
https://deploy-preview-377--cal-itp-website.netlify.app/partners

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@ohmegasquared This is ready for a Design review:

https://deploy-preview-377--cal-itp-website.netlify.app/ - home page logos and new copy
https://deploy-preview-377--cal-itp-website.netlify.app/partners - new page

**Comment by ohmegasquared** [comment]
on the home page, I expected the logos to be in the same column width container as the text above
Screenshot 2024-07-25 at 3 24 56 PM
seeing in netlify going outside of that
Screenshot 2024-07-25 at 3 24 51 PM

on mobile they seem to go off screen
Screenshot 2024-07-25 at 3 28 48 PM


Partners looks great!

**Comment by machikoyasuda** [comment]
@ohmegasquared Ohhhh good catch - thank you! Firefox renders the homepage differently than Chrome and Safari! 🫨 
image

**Comment by machikoyasuda** [comment]
> on the home page, I expected the logos to be in the same column width container as the text above

Fixed and confirmed in Firefox, Safari, Chrome: 
image

**Comment by machikoyasuda** [comment]
This PR is now ready for a _preliminary_ PR review for code (@thekaveman @angela-tran or @lalver1) and design (@ohmegasquared). What I want is a comment here that the Partners section is "Approved for design" or "Approved for code." That will give me the permission to stop working on Partners code/design. You do not need to click the GitHub pull request "Approve" button. That will happen _after_ the copy is in and approved as well.

What I plan to do:
- Monday/Tuesday: Get the Partners PR _preliminary_ approval (code and design)
- Tuesday/Wednesday: Then, get the Customer Stories PR *into* this Partners PR _preliminary_ approval (code and design)
- Wednesday: After the _preliminary_ approvals are done, I don't want to change any code or design. Only copy changes at this point.
- Wednesday/Thursdy: At this point, there will only be 1 PR to manage. In this ONE PR, I'll make all copy/photo changes.

**Comment by ohmegasquared** [comment]
Marissa and I reviewed mobile and web- looks good to us! will make 2 follow up tickets for home dots spacing + footnote adjustment

**Comment by lalver1** [comment]
This looks great! I viewed the pages locally on Firefox and Safari and I'd say it's approved for code.

**Comment by machikoyasuda** [comment]
Fix for #382 applied in this PR

@ohmegasquared

**Comment by ohmegasquared** [comment]
Design is approved on mobile and web! 🔥

**Comment by machikoyasuda** [comment]
New combined PR is here 🎊 🎊 

This preview link has all the new updates: https://deploy-preview-377--cal-itp-website.netlify.app/
https://deploy-preview-377--cal-itp-website.netlify.app/customer-stories
https://deploy-preview-377--cal-itp-website.netlify.app/partners

**Comment by machikoyasuda** [comment]
Update as of Thursday, Aug 1st, 1PM:

- All copy (including alt tags for images/map on Customer Stories) we have is now in the code.
- All pages passing WCAG AA.

Open items:
- CARB quote (for now it's a placeholder)
- MST approval on content and photo
- Glenn County updated photo
- Link to Metabase Dash for Transit Data Quality Dashboard - on the Home page (https://deploy-preview-377--cal-itp-website.netlify.app/#fn:3) and Partners page (https://deploy-preview-377--cal-itp-website.netlify.app/customer-stories#fn:2) - the link is not in there yet b/c the link goes to a page that is inaccessible to non-logged in users

@mrose914 @thekaveman

**Comment by machikoyasuda** [comment]
Lots of small fixes in:
- Fix link styles for the Our impact section and Benefits Monthly Update link
- Fix footnote numbering error
- Add a period in footnote style

**Review by angela-tran — APPROVED** [review]

**Pull request merged**
