### PR TITLE
Refactor: Use Bootstrap container, remove article & constricted

### LINKED ISSUE #123: Refactor: Remove article padding / use Bootstrap cols

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #123 

### Removes Article
- Removes use of `<article>`. 
- Deletes `article` CSS.
- Uses `<main class="container">` in `default.html` layout instead. All pages should now use `<section class="row">` and `<div class="col-6">` syntax logic.

### Removes Constricted
- Removes use of `class="constricted"` and replaces it with `row/col/justify-center`
- Deletes `.constricted` CSS.

## What this PR does NOT do
- Refactor out CSS Grid from Footer, Header (to come in #122), and any other homepage content sections (beyond the "constricted" style)

### Removes Article refactor
image
Note: This header top issue will be fixed in #122 

### Removes Constricted refactor
image
image
<img width="1512" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/135276e3-4ded-4a70-9957-7f942767a131"

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@thekaveman After this PR is merged, rebase this PR with the latest from `staging` https://github.com/cal-itp/calitp.org/pull/118/files and the contents of the Press page should be in a `container`. The Header will still overlap with it until #122 is merged.

**Review by thekaveman — CHANGES_REQUESTED** [review]
This looks mostly really good!

I think using `<section>` for everything here is not semantically correct though. From the [spec](https://html.spec.whatwg.org/multipage/sections.html#the-section-element):

> The [section](https://html.spec.whatwg.org/multipage/sections.html#the-section-element) element is not a generic container element. When an element is needed only for styling purposes or as a convenience for scripting, authors are encouraged to use the [div](https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element) element instead. A general rule is that the [section](https://html.spec.whatwg.org/multipage/sections.html#the-section-element) element is appropriate only if the element's contents would be listed explicitly in the document's [outline](https://html.spec.whatwg.org/multipage/sections.html#outline).

The highest-level elements as `<section>` e.g. `<section id="deck">`, `<section id="details">` seem appropriate, but within those I think `<div>` might be the better choice.

Thoughts?

**Comment by machikoyasuda** [comment]
@thekaveman Yeah - having `<section>`s _inside_ other `<section>`s doesn't make any sense. I think we should change the children `<section>`s in subsequent PRs that actually change the contents. This PR is only concerned with the outermost `<main>` parent (grandparent?).

cc @angela-tran

**Comment by angela-tran** [comment]
I agree we should change the inner `section`s to `div`s. I'm ok with that being done as a separate issue

**Review by angela-tran — APPROVED** [review]

**Review by thekaveman — APPROVED** [review]

**Pull request merged**
