### PR TITLE
Refactor: hero section

### LINKED ISSUE #100: Implement new Hero + border image on Homepage
image

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #100

### CODE REVIEW

**Comment by angela-tran** [comment]
Need to use latest copy from Google Doc

**Comment by angela-tran** [comment]
Made one more commit to remove now-unnecessary CSS. I don't have any more changes in mind for this PR 🙏

**Review by thekaveman — CHANGES_REQUESTED** [review]
This PR is touching more than the hero, e.g. we have other issues for the dividers for other sections, and a large issue for the Initiatives section.

Please focus solely on changes for the top hero section in this PR.

**Comment by angela-tran** [comment]
> This PR is touching more than the hero, e.g. we have other issues for the dividers for other sections.
> 
> Please focus solely on changes for the top hero section in this PR.

I think I understand the concern but am not sure which parts you see as out of scope. I needed to add the "+ border image on Homepage", which caused me to rename the other two dividers. Was that a change you didn't expect?

The other change I think you might be asking me to roll back is my removal of the 3 initiatives.

**Comment by thekaveman** [comment]
> need more detail on which parts you see as out of scope

I mean, _everything_ that is not directly related to the content in the hero section... this PR has a bunch of unrelated stuff. Here are some examples I pulled from the commits:

* b4df91cb599bc6d3ba4f8f8da6c4eecfb633520c (this entire commit is about the Initiatives section)
* https://github.com/cal-itp/calitp.org/pull/115/commits/84f84bb2dc1261c93eb8521757b01dc3657f421a#diff-4e9ead19074dc06fa9b4dce5cbbb7b06d97725dc022be3f4263abf99a02ec64fR11 (highlighting a change to `h4` element, not part of hero)
* https://github.com/cal-itp/calitp.org/pull/115/commits/606354273879d55c5708fb88da851d938097fde9#diff-4e9ead19074dc06fa9b4dce5cbbb7b06d97725dc022be3f4263abf99a02ec64fR32 (highlighting changes to `li`, not part of hero)
* f482e1f476c69df8045f012b61825a6f38e81bf6 (this entire commit is about the Initiatives section)

**Comment by angela-tran** [comment]
Talked with @thekaveman - I'm going to close this PR and start a new one that doesn't change any Initiatives code

**Pull request closed without merging**
