### PR TITLE
update wording around Benefits eligibility verification

### PR DESCRIPTION
**Pull request by afeld**
Updates to reflect the new flow that uses Login.gov. We might want to wait to merge this until the changes are released: https://github.com/cal-itp/benefits/issues/635

### CODE REVIEW

**Review by esquared415 — APPROVED** [review]
This looks great @afeld! 

In terms of when to pub this change: I agree that we should wait until the first screen of the Benefits tool reflects new login.gov approach (right now, https://benefits.calitp.org/ is displaying DMV login screen).

_But_ calitp.org doesn't get a ton of traffic, so if you need to / want to pub this change earlier just to get it out of the way, we'll be fine. 😄

**Comment by afeld** [comment]
The change is live, so let's merge!

**Comment by thekaveman** [comment]
Please hold on merging this to align with the broader Cal-ITP comms strategy.

**Comment by esquared415** [comment]
We are ready to move forward with pushing this content change live. But first, please update the URL linked from "Monterey-Salinas Transit"; the new link should be: 
[Monterey-Salinas Transit]
(https://mst.org/news_items/monterey-salinas-transit-mst-announces-discount-contactless-fares-for-both-local-and-visiting-riders-65-with-launch-of-new-benefits-eligibility-verification-website/)

Thanks, @thekaveman and team!

**Comment by thekaveman** [comment]
@afeld see comments for pushing this live above from @esquared415

**Pull request merged**
