### PR TITLE
Initiatives:  Add 16px total vertical padding between links

### LINKED ISSUE #236: Increase spacing between links within initiatives section to 16px
Currently the spacing between links within each of the Initiatives on the homepage of calitp.org is a little hard to read. Request from the team is to double (from 8px > 16px) the spacing to provide more space between articles/docs. 

cc @segacy1 @esquared415

### PR DESCRIPTION
**Pull request by machikoyasuda**
fix #236 

image

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@segacy1 Ready for design review

**Comment by segacy1** [comment]
Thank you @machikoyasuda! Could you double-check that the space between the last link and "see all" is also 16px? Otherwise good to go

**Comment by machikoyasuda** [comment]
@segacy1 Good catch! I added a bit more padding-top to See all, so it has the same spacings as the rest of the links now. https://deploy-preview-237--cal-itp-website.netlify.app/

**Review by thekaveman — APPROVED** [review]
This LGTM

**Pull request merged**
