### PR TITLE
Fix: initiatives sections spacing

### PR DESCRIPTION
**Pull request by angela-tran**
Part of https://github.com/cal-itp/calitp.org/issues/177

> adjust vertical spacing for all sections to 40px Desktop, 28px Mobile

### CODE REVIEW

**Comment by angela-tran** [comment]
Going to rebase

**Review by thekaveman — COMMENTED** [review]
I'm OK with introducing this helper class since it seems like 40px is not exactly within the Bootstrap `mb-*` framework. Wondering if @machikoyasuda has any thoughts on this approach?

Also, nitpick, but it feels a little strange to me to have the margin applied to the Initiatives button vs. its parent `div`, but this also works, so I won't block because of it.

**Comment by machikoyasuda** [comment]
What about splitting this class up into 2 classes, and using this naming scheme:
- `mb-md-40`: `margin-bottom` of 40px at `md` widths and above
- `mb-28`: `margin-bottom: of 28px

and then this way, these classes can be re-used if there are any other places that need either of these declarations.

**Comment by angela-tran** [comment]
> What about splitting this class up into 2 classes, and using this naming scheme:
> 
>     * `mb-md-40`: `margin-bottom` of 40px at `md` widths and above
> 
>     * `mb-28`: `margin-bottom` of 28px
> 
> 
> and then this way, these classes can be re-used if there are any other places that need either of these declarations. And since the class names correspond mostly with Bootstrap's spacing schemes, it's easier to read for others.

I'm ok with this approach. The reusability is nice

**Comment by thekaveman** [comment]
Oof, this seems like one of those times where there shouldn't have been a merge conflict... annoying

**Comment by angela-tran** [comment]
Rebased to resolve conflicts. This is ready for re-review

**Review by thekaveman — APPROVED** [review]
Nice! I like the generalization of the helper classes, LGTM!

**Pull request merged**
