### PR TITLE
Fix: Home - Desktop - Dot spacing

### LINKED ISSUE #383: Spacing for dividers
on homepage:
- first dot divider spacing top: 0px
- first dot divider spacing bottom: 64px
- dividers between impact + contact spacing above: 0px (there seems to be spacing in the impact container)

### PR DESCRIPTION
**Pull request by machikoyasuda**
fixes #383

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@ohmegasquared How does this look? https://deploy-preview-384--cal-itp-website.netlify.app/ Can you check both Desktop and Mobile?

**Comment by ohmegasquared** [comment]
Looks ready to ship on web

On mobile (sorry forgot to add in the description) there is extra space
- first dots before: total should be 1.5rem 
- first dots after: total should be 2rem
Screenshot 2024-07-31 at 12 37 19 PM

-second dots before: can we remove 1rem from the margin?

-third dots before: update to 1rem
-third dots after: update to 2rem

**Comment by ohmegasquared** [comment]
awesome! mobile and web designs approved

**Comment by machikoyasuda** [comment]
@thekaveman @angela-tran @lalver1 this is ready for code review! it's been reviewed + approved by Design.

**Review by thekaveman — APPROVED** [review]

**Pull request merged**
